# Generated by Django 5.2.15 on 2026-07-07 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_history', models.TextField(blank=True, help_text='Maladies chroniques (diabète, hypertension, etc.), hospitalisations passées.', verbose_name='Antécédents médicaux')),
                ('surgical_history', models.TextField(blank=True, help_text='Opérations subies (avec dates si possible).', verbose_name='Antécédents chirurgicaux')),
                ('family_history', models.TextField(blank=True, help_text='Maladies héréditaires ou récurrentes dans la famille (ex: maladies cardiaques, cancers).', verbose_name='Antécédents familiaux')),
                ('allergies', models.TextField(blank=True, help_text='Médicaments (ex: pénicilline), aliments, latex. Indispensable pour bloquer une mauvaise prescription.', verbose_name='Allergies et contre-indications')),
                ('risk_factors', models.TextField(blank=True, help_text="Tabagisme, consommation d'alcool, profession (exposition à des risques). Le groupe sanguin est déjà dans le modèle Patient.", verbose_name='Facteurs de risque / Mode de vie')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to='patients.patient')),
            ],
        ),
    ]
