# Generated by Django 5.2.15 on 2026-06-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('DOCTOR', 'Médecin'), ('RECEPTIONIST', 'Réceptionniste'), ('CLIENT', 'client')], default='CLIENT', max_length=20),
        ),
    ]
