# Generated by Django 5.2.15 on 2026-06-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('DOCTOR', 'Médecin'), ('RECEPTIONIST', 'Réceptionniste'), ('CLIENT', 'client'), ('PHARMARMACIST', 'Pharmaceutique')], default='CLIENT', max_length=20),
        ),
    ]
