# Generated by Django 5.2.15 on 2026-07-02 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('chronic_diseases', models.TextField(blank=True, help_text='Diabète, hypertension, etc.')),
                ('family_history', models.TextField(blank=True, help_text='Maladies héréditaires dans la famille')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.CharField(help_text="Nom de l'allergène (ex: Pénicilline, Arachides)", max_length=100)),
                ('reaction', models.TextField(blank=True, help_text='Type de réaction (ex: éruption cutanée, choc anaphylactique)')),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Sévère (Urgence)')], default='MEDIUM', max_length=10)),
                ('discovered_on', models.DateField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='medical_records.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(help_text="Nom de l'intervention (ex: Appendicectomie)", max_length=200)),
                ('surgery_date', models.DateField(blank=True, null=True)),
                ('hospital_name', models.CharField(blank=True, help_text="Où l'opération a eu lieu", max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='medical_records.medicalrecord')),
            ],
        ),
    ]
