# Generated by Django 5.2.15 on 2026-06-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_remove_prescription_dosage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
