# Generated by Django 5.2.15 on 2026-07-09 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_stockmovement_adjustment_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='dosage_form',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='quantity_in_stock',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='medicine',
            name='stock_min',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='Medicine_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('numero_lot', models.CharField(max_length=200)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='medicines.medicine')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='medicines.medicine_type'),
        ),
    ]
