# Generated by Django 5.2.15 on 2026-07-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_medicine_type_remove_medicine_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=100),
        ),
    ]
